Adds listen gem to gemspec. Fixes: LoadError: Could not load the 'listen' gem when running ‘calagator new appname’
LoadError: Could not load the 'listen' gem. Add `gem 'listen'` to the development group of your Gemfile
Caused by:
LoadError: cannot load such file -- listen
/environment.rb:5:in `<main>'